### ISSUE TITLE
Should betalogpdf return -Inf outside the unit interval instead of throwing an error?

### ISSUE THREAD

**Issue by fernando-duarte** [JuliaStats/StatsFuns.jl#116]
I ran into the issue while running some Turing.jl code, MWE and original post here:

_Original post by @fernando-duarte in https://github.com/TuringLang/AdvancedHMC.jl/issues/266#issuecomment-872965148_

**Comment by devmotion** [comment]
I think this should be taken into account in https://github.com/JuliaStats/StatsFuns.jl/pull/113.

**Comment by fernando-duarte** [comment]
Not yet merged but will work, yes!

**Comment by fernando-duarte** [comment]
PS. I checked and issue is not solved by #113 as it currently stands. I left a comment there, and a proposed solution that was wrong -- so hopefully someone more knowledgeable will be able to take care of it.
