### ISSUE TITLE
GPL contamination by requiring Rmath

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaStats/StatsFuns.jl#17]
StatsFuns is much too important a Julia package to be contaminated with GPL.
E.g., required by StatsBase, which is required by DataFrames.

**Comment by johnmyleswhite** [comment]
This is well understood and will be worked on. The best thing you can do is help write code to make it possible to remove the dependency on Rmath.

**Comment by nalimilan** [comment]
Yes, better open an issue with a list of functions that still need a pure Julia implementation.

**Comment by andreasnoack** [comment]
A few remarks

- The dependencies between the stats packages are a bit of a mess right now. `StatsBase` shouldn't depend on `StatsFuns`. If anything, it should be the other way around. I don't think it should be too hard to remove that dependency.

- It's unlikely that the functionality in `StatsFuns` can be supported without `Rmath` anytime soon. Some of the functionality is almost replaced by Julia implementations, e.g. generating random numbers for a variety of distributions but the special function implementations in `Rmath` are quite skill and labor intensive.

**Comment by nalimilan** [comment]
> The dependencies between the stats packages are a bit of a mess right now. StatsBase shouldn't depend on StatsFuns. If anything, it should be the other way around. I don't think it should be too hard to remove that dependency.

Why? StatsFuns provides low-level statistical functions which can be needed in StatsBase. For example, to do a Chi-squared test, you need the corresponding distribution functions.

That said, I think the general idea is that one should use Distributions.jl instead of StatsFuns.jl. (I also remember discussions about merging these again.)

**Comment by tlnagy** [comment]
Is there any movement on shifting the requirement of StatsBase to Distributions over StatsFuns?

**Comment by andreasnoack** [comment]
`StatsBase` doesn't depend on any of them. A side note. `StatsFuns` was factored out from `Distributions` at some point for modularity but I'd actually like that it returns to `Distributions`. They shouldn't really be considered alternatives.

**Comment by tlnagy** [comment]
That makes a lot of sense.
