### ISSUE TITLE
trouble with StatsFuns

### ISSUE THREAD

**Issue by nbecker** [JuliaStats/StatsFuns.jl#19]
I'm trying to port a simple python script using chi-square and noncentral chi-square.  I can't seem to find any doc on chisqccdf and nchisqcdf, so guessing on the parameters.  The original is here:
http://pastebin.com/vTf1ay3S

The julia version is here:
http://pastebin.com/wLjmFYA1

The results are completely different.  It almost seems as if the role of cdf and ccdf are swapped.  It's not possible for cdf to decrease, for example.

But even if I try swapping ccdf<->cdf, it doesn't make sense.  For chi-square with df=2, we have exponential, which should produce a straight line on a log plot (as the python code does), but the julia code doesn't produce a straight line.

What am I missing?  And, is there some way I could get the documentation on these functions?

**Comment by johnmyleswhite** [comment]
You should work with Distributions.jl and not use this package. This package is not meant for end-users and I will change the documentation to make that clear.

**Comment by nbecker** [comment]
Thanks!
Don't see non-central chi-square in the doc for Distributions.jl, though

**Comment by ararslan** [comment]
I think the docs for Distributions.jl are a little out of date. Check out `NoncentralChisq(ν, λ)` from that package.

**Comment by johnmyleswhite** [comment]
Can you file an issue for documentation against that repo then? Even better, can you write some documentation for the code here: https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/continuous/noncentralchisq.jl
