### ISSUE TITLE
logsumexp([-Inf,-Inf]) incorrect (gives NaN)

### ISSUE THREAD

**Issue by tpapp** [JuliaStats/StatsFuns.jl#22]
The correct value would be `-Inf`. The bug occurs because the maximum is `-Inf`, resulting in a `-Inf - (-Inf)==NaN`. Catching `u == -Inf` and returning `-Inf` is a possible solution.

Two-argument `logsumexp` has the same problem.

Unless the maintainers prefer to make this trivial change, I can make up a PR (with tests).

**Comment by tpapp** [comment]
And a minor point: it is not type stable either, eg `logsumexp(Float32[]) == Inf`, not `Inf32`.

**Comment by andreasnoack** [comment]
Usually, we use "type stable" to mean that the return type depends on the value of the input. In this case, the function just promotes the input to `Float64` which is type stable but might not what you want. I think changing it such that it becomes generic would be useful and a PR for both changes (probably separately) would be appreciated.

**Comment by tpapp** [comment]
Will do it, and review other functions too.

Implementation detail: is there a function similar to `one(T)` and `zero(T)` for various infinities?

**Comment by andreasnoack** [comment]
Not that I'm aware of. I usually do `T(Inf)`.

**Comment by tpapp** [comment]
Added PR #23. Thanks for your help.
