### ISSUE TITLE
Writing generics so as to handle BigFloat and Dual

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/StatsFuns.jl#34]
I created a branch `genericpois` with generic versions of `poispdf` and `poislogpdf` and then found that it failed the tests I added.  I had forgotten that the initial reason for adding such generic methods was to handle dual numbers cleanly.  I was more interested in allowing for `BigFloat` and `BigInt`.

I was careful to return a value of the same type as the first argument and to evaluate the log-factorial of `x` as
```julia
lgamma(oftype(λ, x + one(x)))
```

But causes problems when the first argument is a numeric value and the second is a `Dual`.

Correct me if I am wrong but I don't see a purpose in writing a probability mass function for a Dual argument.  Nevertheless, I don't want to botch the testing.  However, I also don't want to lose precision by failing to evaluate `lgamma` on a `BigFloat` when the result is going to be combined with BigFloats.

I have a version that sort-of works now but requires many multiplications by `one(z)` where `z` is an argument in order to preserve both precision and the ability to hand Dual numbers as arguments.

**Comment by andreasnoack** [comment]
Wouldn't something like this work
```julia
poislogpdf(x::T, λ::T) where {T<:Real} = x*log(λ) - lgamma(x + 1) - λ

poislogpdf(x::Number, λ::Number) = poislogpdf(promote(x, λ)...)
```

**Comment by dmbates** [comment]
Yes, thank you.  A much cleaner solution than what I was trying.  I have updated that branch accordingly.

It turns out that it doesn't deal with a combination of `Dual` and `BigFloat` because there is no promotion rule for that combination but that is not an important issue here.

**Comment by tpapp** [comment]
> don't see a purpose in writing a probability mass function for a Dual argument

@dmbates: it is advantageous if anything that may be used in a likelihood is autodiff-able, so that it can be used with

1. HMC methods for Bayesian inference,
2. derivative-based optimizers for ML/MAP

I rely on this routinely.

**Comment by dmbates** [comment]
@tpapp Of course, it is worthwhile allowing for evaluation of a `pdf` or `logpdf` method using `Dual` numbers for the parameters.  What had me confused in the use in `test/generic.jl` where it is the argument that is passed as a `Dual`.  That doesn't make sense of a discrete probability mass function.
