### ISSUE TITLE
Is tvpack.jl still needed?

### ISSUE THREAD

**Issue by dmbates** [JuliaStats/StatsFuns.jl#43]
I don't think that `src/tvpack.jl` is ever included in this package and I was wondering why it is in the sources?

**Comment by andreasnoack** [comment]
I think the reason is that it might be useful but nobody has ever added the relevant methods that would use these. Part of problem is the lack of generality since these functions only handle 2 and 3d whereas the multivariate distributions are theoretically defined for any dimension.

**Comment by cynddl** [comment]
Since tvpack.jl is in the source code, any chance the file can be included in _StatsFuns.jl_? Thanks!
The routines are quite useful as they don't require to use the original Fortran code.

**Comment by andreasnoack** [comment]
The file was included again in #67
