### ISSUE TITLE
logsumexp fallback for Base.Iterators.Filter

### ISSUE THREAD

**Issue by konkam** [JuliaStats/StatsFuns.jl#63]
Except for AbstractArrays, `logsumexp` falls back to `reduce(logaddexp, X)`, see: https://github.com/JuliaStats/StatsFuns.jl/blob/316cebb69d4e28e6a4b17d72eee112e61c3b9b77/src/basicfuns.jl#L191

Reduction to adding each element sequentially is numerically less stable than the `sum` function, the issue is mentioned here for instance: https://discourse.julialang.org/t/julia-equivalent-of-pythons-fsum-for-floating-point-summation/17785/27

I have encountered this fallback when using logsumexp on a iterator with a filtering condition:

```
julia> logsumexp(i for i in range(-500, stop = 10, length = 1000) if true) - logsumexp(range(-500, stop = 10, length = 1000))
-1.7763568394002505e-15
```

This may not be a problem related only to logsumexp, maybe the iterator with a filtering condition should also be dealt with as an AbstractArray

**Comment by nalimilan** [comment]
Unfortunately I'm not sure we can do much about this at the moment. First, Julia itself doesn't use the more accurate pairwise summation algorithm for non-arrays (https://github.com/JuliaLang/julia/issues/30421), so we can't compute the precise sum. Then, we need to compute the maximum before computing the sum, which requires doing two passes over the data. But for some iterables, computing each element may be costly or even not possible.

I guess we could have a special case for generators at least, assuming that doing two passes won't be too slow. Or an argument to choose between the fast less accurate method and the possibly slower but accurate one.

**Comment by konkam** [comment]
Ok, many thanks for the reply and the pointer to the similar issue.

**Comment by devmotion** [comment]
This was fixed by https://github.com/JuliaStats/StatsFuns.jl/pull/97, with StatsFuns 0.9.6 I get
```julia
julia> logsumexp(i for i in range(-500, stop = 10, length = 1000) if true) - logsumexp(range(-500, stop = 10, length = 1000))
0.0
```

**Comment by nalimilan** [comment]
Cool!
