### ISSUE TITLE
RFunctions `binom` definitions shadow generic ones

### ISSUE THREAD

**Issue by hycakir** [JuliaStats/StatsFuns.jl#64]
`binomlogpdf(10, BigFloat(0.3), 3)` returns `Float64` falling back to `RFunctions` definitions. Generic definitions are called only if `x <: Union{Float64, Int}` is false.

https://github.com/JuliaStats/StatsFuns.jl/blob/316cebb69d4e28e6a4b17d72eee112e61c3b9b77/src/rmath.jl#L51-L59

**Comment by andreasnoack** [comment]
Maybe we should simply change https://github.com/JuliaStats/StatsFuns.jl/blob/316cebb69d4e28e6a4b17d72eee112e61c3b9b77/src/rmath.jl#L51 to `Union{Int,Float64}` instead of `Real` to avoid these silent truncations to `Float64`.

**Comment by andreasnoack** [comment]
Silent promotion from `Float32` to `Float64` would generally be quite unfortunate, though, so I think this change would be worth it. I'd even consider restricting the methods that ccall Rmath to be restricted to `Float64` only and then promote integers explicitly to avoid any of the conversions to happen in ccall where they are well hidden.
