### ISSUE TITLE
Arrays in addition to numbers to generate an array of some elements

### ISSUE THREAD

**Issue by aoboturov** [JuliaStats/StatsFuns.jl#7]
There is only one element generated at a time functions in the package, e.g.:

   normpdf(μ::Real, σ::Real, x::Number)

would produce only one number, `x` could not be array.

Although one could write:

    xs = [1, 2, 3]
    ps = [normpdf(0, 1, x) for x=xs]

why one could not just write:

    xs = [1, 2, 3]
    ps = normpdf(0, 1, xs)

?

**Comment by johnmyleswhite** [comment]
A couple of comments:

* You should try using the Distributions package. You're not really supposed to use `normpdf` in StatsFuns unless you have a specialized use case.

* There's a strong technical argument against your proposal: you're forcing the `normpdf` function to duplicate functionality that's already available elsewhere. While this is potentially convenient for users, it leads to an unmaintainable system that can't be worked on by engineers. It's vastly better to keep the concept of repeated computation orthogonal to the concept of evaluating the pdf of the normal distribution.

**Comment by nalimilan** [comment]
The issue of easy vectorization is more general and has been discussed at length here: https://github.com/JuliaLang/julia/issues/8450.

**Comment by aoboturov** [comment]
Thanks. Do you have a pdf or a talk where the whole of JuliaStats organisation is explained.

Plus now I kind of see why there's no documentation whatsoever for this package.

**Comment by johnmyleswhite** [comment]
I'm not aware of such a document. Hopefully someone will create one at some point.

The packages that are meant for public use tend to be documented, sometimes very thoroughly (e.g. Distributions).

I would very strongly encourage you to ask questions on the julia-users mailing list as you learn the lay of the land. There are many people who are familiar with the JuilaStats package and they can help you.

**Comment by aoboturov** [comment]
Indeed.
