### ISSUE TITLE
logsumexp for Tuples

### ISSUE THREAD

**Issue by cossio** [JuliaStats/StatsFuns.jl#75]
`logsumexp(X::Tuple)` currently falls back to `reduce(logaddexp, X)`, which is slower and numerically less stable than the array fallback.

Since we can compute the `maximum` of a `Tuple`, can we use the array fallback here too?

Related: https://github.com/JuliaStats/StatsFuns.jl/issues/63

**Comment by nalimilan** [comment]
Yes, probably.
