### ISSUE TITLE
function fdistcdf

### ISSUE THREAD

**Issue by Peichao** [JuliaStats/StatsFuns.jl#84]
Hi, I am new to Julia.  I find that the result from function fdistcdf is different from the result of matlab function fcdf. For example, fdistcdf(0.2, 2, 3) = 0.8636102539827808, but fcdf(0.2,2,3, 'upper') = 0.828826267612698. Do I use fdistcdf correctly? Thank you!

**Comment by nalimilan** [comment]
StatsFuns isn't really meant to be used directly. Use Distributions.jl instead as it provides a much more user-friendly interface:
```julia
julia> using Distributions

julia> ccdf(FDist(2, 3), 0.2)
0.8288262676126976
```

**Comment by Peichao** [comment]
Thank you!
