### ISSUE TITLE
Rational param breaks Binomial CDF

### ISSUE THREAD

**Issue by ron-wolf** [JuliaStats/StatsFuns.jl#98]
`StatsFuns.binomccdf()` maps to the eponymous R function, as shown below.

https://github.com/JuliaStats/StatsFuns.jl/blob/d99fdf43d40a70ca7a688e11afba1a84963eb396/src/distrs/binom.jl#L3-L13

However, when called on a binomial distribution with `𝑝::Rational`, an error occurs; currently, the only option is to convert the parameter using `float()`. Note that although the code below uses Distributions, I believe the error is on the part of StatsFuns: see [this code in Distributions](https://github.com/JuliaStats/Distributions.jl/blob/20c91d9efcc5f96913bf8e38be2e3fb14b21942b/src/univariates.jl#L541-L557) for the call to StatsFuns.

```julia
using Distributions; ccdf(Binomial(7, 1//5), 1)
```
```
ERROR: MethodError: no method matching binomccdf(::Int64, ::Rational{Int64}, ::Int64)
Closest candidates are:
  binomccdf(::Union{Float64, Int64}, ::Union{Float64, Int64}, ::Union{Float64, Int64}) at /Users/USER/.julia/packages/StatsFuns/CXyCV/src/rmath.jl:80
Stacktrace:
 [1] ccdf(::Binomial{Rational{Int64}}, ::Int64) at /Users/USER/.julia/packages/Distributions/RAeyY/src/univariates.jl:557
 [2] top-level scope at REPL[1]:1
```

Is this intended behavior? Such distributions work just fine with `StatsPlots.plot()`.

```julia
using Distributions, StatsPlots; plot(Binomial(7, 1//5))
```

![A plot of the binomial distribution with n=7 and p=⅕](https://user-images.githubusercontent.com/7342888/85506967-72f10300-b5bf-11ea-9d2e-bfdf86818928.png)

**Comment by andreasnoack** [comment]
The cdf of the Binomial distribution is based on the incomplete Beta function which is very complicated function to implement reliably. However, I guess we could have a naive fallback that sums up the probabilities.

**Comment by ron-wolf** [comment]
Certainly! I’d be happy to get involved in implementing this. I’m relatively new to Julia though, as well as to statistics generally. I have a few questions:

- Do you happen to know where I’d find R‘s implementation of the binomial CDF? It is my understanding that Julia uses it.
- Do you suspect that when properly implemented, this fallback will involve numerical integration using, e.g., [QuadGK](https://juliamath.github.io/QuadGK.jl/latest/)?

**Comment by ron-wolf** [comment]
Related: #33

**Comment by devmotion** [comment]
The issue was fixed by https://github.com/JuliaStats/StatsFuns.jl/pull/125. With StatsFuns 0.9.11:
```julia
julia> using Distributions; ccdf(Binomial(7, 1//5), 1)
0.4232832000000002
```
